resources:
- ../../../base/api-server

images:
  - name: nginx
    newName: nginx
    newTag: "1.25"

 #patchesStrategicMerge:
 #- dev-patch.yaml

patches:
- path: dev-patch.yaml

namespace: dev
namePrefix: dev-

# configMapGenerator
configMapGenerator:
- name: env-vars        
  envs:
    - dev.env
